### ISSUE TITLE
Exchange events between workers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1593]

**Comment by tshemsedinov** [comment]
Done: https://github.com/metarhia/impress/pull/1607

**Comment by lundibundi** [comment]
Looks like it is still not possible to exchange "custom" events between workers. Could you point to examples or code so that I could take a look?
